apiVersion: v1
kind: Namespace
metadata:
  name: prod

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: prod
spec:
  hard:
    requests.cpu: '1.5' # 1500m
    requests.memory: '2Gi'
    limits.cpu: '2.5'
    limits.memory: '3Gi'