apiVersion: v1
kind: Pod
metadata:
  name: color-api
  labels:
    app: color-api
spec:
  containers:
  - name: color-api
    image: saputra523/color-api:1.2.1
    ports:
      - containerPort: 80
    resources:
      requests:
        cpu: '200m'
        memory: '256Mi'
      limits:
        cpu: '400m'
        memory: '512Mi'
    env:
      - name: DELAY_STARTUP
        value: 'false'
      - name: FAIL_LIVENESS
        value: 'false'
    startupProbe: 
      httpGet:
        path: /up
        port: 80
      failureThreshold: 2
      periodSeconds: 3
    livenessProbe: 
      httpGet:
        path: /health
        port: 80
      failureThreshold: 3
      periodSeconds: 10
    