apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
  labels:
    app: traffic-generator
spec:
  containers:
  - name: traffic-generator
    image: saputra523/traffic-gen:1.0.0
    args:
      - 'color-api-svc/api'
      - '0.5'
    resources:
      requests:
        cpu: '200m'
        memory: '256Mi'
      limits:
        cpu: '400m'
        memory: '512Mi'
    