FROM node:22-alpine

WORKDIR /app

COPY package.json .
COPY pnpm-lock.yaml .

# Build Phase

RUN npm install -g pnpm

# Run Phase
RUN pnpm install --prod

COPY index.js index.js

CMD ["node", "index.js"]